### ISSUE TITLE
Collectstatic fails on django 2.1.1

### ISSUE THREAD

**Issue by nawilliams** [rbennett91/django-tabler#1]
I'm getting the following error when I run collectstatic using this package along with django 2.1.1 and whitenoise 4.1 
```
$ python manage.py collectstatic

Post-processing 'fonts/font_awesome/font-awesome.min.css' failed!

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/project-iEzfxys1/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/project-iEzfxys1/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/project-iEzfxys1/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/project-iEzfxys1/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/root/.local/share/virtualenvs/project-iEzfxys1/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in
handle
    collected = self.collect()
  File "/root/.local/share/virtualenvs/project-iEzfxys1/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in
collect
    raise processed
whitenoise.storage.MissingFileError: The file 'fonts/fonts/fontawesome-webfont.eot' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7ff60f51eda0>.

The CSS file 'fonts/font_awesome/font-awesome.min.css' references a file which could not be found:
  fonts/fonts/fontawesome-webfont.eot

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

If I had to guess the relative paths in a bunch of the files aren't correct. I ended up adding the source files for tabler to my repo and ran into the same issue in the iconfonts plugin css file, which I fixed by changing a number of paths.

**Comment by lemanou7** [comment]
hello how did you fix the paths. I have the same problems for weeks and don't know how to fix it.Thanks

**Comment by nawilliams** [comment]
I straight deleted this django plugin and manually installed tabler. I can't tell you exactly how as this was over a year ago but here are the related commits. There were some additional issues I remember having with the tabler asset paths for getting the included javascript packages to work. Sorry I can't help more, I haven't touched django since then.

https://github.com/fuseumass/hackerforce/commit/ed8f6c31f58815a3e307f1675d2b344ac237fe1e
https://github.com/fuseumass/hackerforce/commit/477c389f9bbe8d289967cc1cd1448fac17f4d826
https://github.com/fuseumass/hackerforce/commit/2a789ea103cc4a823b2375a1b7e598cde3bf3ce6
https://github.com/fuseumass/hackerforce/commit/b4c89afd4e29d1c0ca5a25ee201e7305d2698b3f
https://github.com/fuseumass/hackerforce/commit/79fa958072a6aff1797f13aaf052d46c169530e2
